version: 2

models:
  - name: stg_addresses
    description: Address info
    columns:
      - name: address_id
      - name: address
      - name: zipcode
      - name: state
      - name: country
  - name: stg_events
    description: Events info
    columns:
      - name: event_id
      - name: session_id
      - name: user_id
      - name: event_type
      - name: page_url
      - name: created_at
  - name: stg_order_items
    description: Order items info
    columns:
      - name: order_id
      - name: product_id
      - name: quantity
  - name: stg_orders
    description: Orders info
    columns:
      - name: order_id
      - name: promo_id
      - name: user_id
      - name: address_id
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status
  - name: stg_products
    description: products info
    columns:
      - name: product_id
      - name: name
      - name: price
      - name: quantity
  - name: stg_promos
    description: promos info
    columns:
      - name: promo_id
      - name: discount
      - name: status
  - name: stg_users
    description: users info
    columns:
      - name: user_id
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id